### ISSUE TITLE
Precomputed technique gives same start time for different snippets when using larger data sets

### ISSUE THREAD

**Issue by eamonnkenny** [dpwe/audfprint#17]
I am precomputing the pklz files for a mixture of wav and mp3 files that make up a collection of 68 large files. Then I am seeing whether 1249 snippets appear in one of these 68 larger files.

Interesting, i always find that the last value is wrong and the same as the penultimate value, as if there is an algorithmic error. 

Example:

And the Penultimate and last value show the same start times also:
Matched precomp/source/aud/20100216_LeadersQuestions.afpt 409.9 sec 14841 raw hashes as segmented/aud/Po01PtFG_20100216_st_0019.wav at -275.7 s with   590 of   662 common hashes at rank  8
Matched precomp/source/aud/20100216_LeadersQuestions.afpt 409.9 sec 14841 raw hashes as segmented/aud/Po01PtFG_20100216_st_0010.wav at -275.7 s with   585 of   662 common hashes at rank  9

This problem does not arise if I create a much smaller number of .afpt files and send all segmented/aud/Po01PtFG_20100216_st_*.wav into it.  

I'm wondering am I running the code with slightly wrong options and this is the cause of the problem? If I run with density = 100 I get a few snippets of duration > 10secs that are not recognised in using the algorithm. If I set density = 50 I get only snippets < 2.5secs that are not recognised which I would be throwing away anyway. If I have much smaller densities I obtain more and more NOMATCH values.

My script for running the software looks something like this:

ls source/aud/_.wav source/aud/_.mp3  > largeFiles.list
ls segmented/aud/_$2_ > allSnippets.list

rm -rf precomp

echo "Precompute peaks for all large files..."
./audfprint.py precompute --samplerate 11024 --density 50 --shifts 1 --precompdir precomp --ncores 4 --list largeFiles.list
find precomp/ -name "*.afpt" > precomp.list

echo "Take the snippets and build a database of their peak profiles..."
./audfprint.py new   --dbase snippets.db --density 50 --samplerate 11025 --shifts 4 --list allSnippets.list

echo "Lastly, find matches and arrange on screen to make the information easier to read..."
./audfprint.py match --dbase snippets.db --match-win 2 --min-count 20 --max-matches 100 --sortbytime --opfile matches.txt --ncores 4 --list precomp.list

echo "Check against known results..."
grep Matched matches.txt | sed -e "s@precomp@@" -e "s@/2/data/@@g" -e "s/.mp3//" -e "s/.wav//" -e "s/.afpt//" | awk '{printf "%s\t%2d:%2.1f\t%s\n",$15,(-$11%3600/60),(-$11%60),$9}' > recognised.txt

**Comment by eamonnkenny** [comment]
Actually turns out that the first set of start times are correct, but its only the penultimate and ultimate values that are always the same even though they should be different. The last value show have a start time of 3.5 secs instead of 275.7 secs. I tried running it with ncores=1 to see if it was some sort of multithreading issue but I still obtain the same results.

**Comment by dpwe** [comment]
Most likely it's a time aliasing issue.  In order to keep the database
small, the time offsets for each landmark are held in fixed-size integers;
by default, it's 14 bits (controlled by --maxtimesize 16384).  Any time
offsets within tracks that exceed this value wrap back to the range
0..16383.  This doesn't (much) affect the fingerprint comparison, since the
time *differences* are the same as long as both times being compared are
wrapped into the same interval.  But it can drastically affect the absolute
times reported.

The units of the time differences are 256 sample frames, or 23 ms at 11 kHz
sampling, meaning that times larger than ~6 min will be aliased (your time
is smaller than this, maybe your sampling rate is higher?).  In any case,
increasing --maxtimesize to 65536 should help (you'll have to recompute the
whole database).  Using more bits for the timing information steals bits
from the item ID, so that will reduce the maximum number of reference items
to 65536 also; hopefully, this doesn't affect your application.

This has come up before, so I think it's correct to class it as a bug.  I
guess the solution is to have some noisy warning when ingesting items whose
time duration causes a wrap of the timing info.  It's only a problem when
reporting time ranges, but the program shouldn't be reporting flat-out
wrong times without warning.

  DAn.
