### ISSUE TITLE
search by track id/name?

### ISSUE THREAD

**Issue by shuvuu** [dpwe/audfprint#22]
Hello, 
Is it possible to search in hashes which track_id or filename is known? not from whole database? If possible where can I begin? I am new to python and don't understand the codes very well. I need some help please.

I believe that if database is huge (1000 s of tracks) and lot of query takes lot of resources and time, right? This filtering helps a lot? or not?

**Comment by dpwe** [comment]
There's no way to do this at present.  The index lookup is "inverted", so it's sublinear in the number of reference items, but it does get slower for large databases.

One way to do it would be build multiple small reference databases, such that they were subsetted in a useful way (maybe by some hash of title, if you want to limit by title), then only query against some of them.  There's no natural way to speed up the search on a large index if you know that only a subset of ref items are candidates.

**Comment by shuvuu** [comment]
Thank you for reply. 
I've another question. Is it possible to search certain part of precomputed or original file? First, I'd like to search using A db, then search using B db on unmatched part of the file.  I don't want to search again already matched parts of the file.

 I tried - extract unmatched part of file to new audio file and .... - works but complicated and slow.

**Comment by dpwe** [comment]
I don't think there's a huge advantage to restricting matches to just some part of the query file rather than the whole file; the marginal cost of searching for matches in the part you've already accounted for isn't great.

But it would be possible to add this: in audfprint_match:match_files, add some options to indicate a subregion, then after calculating q_hashes (which is a list of (time_step, hash) pairs), simply discard all the elements whose time_step is not within the desired range.  This would make the most sense with precomputed query files, otherwise you'd still be re-computing the hashes for the part you don't want to match, which is a significant part of the computation.
