### ISSUE TITLE
Scaling Question

### ISSUE THREAD

**Issue by aldycool** [dpwe/audfprint#23]
Hi,

I have a few questions regarding scaling:

1. Considerng current implementation of HashTable, which holds 1,048,576 unique hashes with each hash holds 100 entries, you've explained that this configuration is able to store more than 100k song tracks. If I have millions of song tracks, would it lessen the accuracy of detection against all the millions of song tracks? Because I understand that when the bucket is filled (over 100 entries) for a specific hash, that specific hash's bucket it gets randomly replaced in a random position of the entries between 1 to 100 (replaced by new song / track id). 

2. If number 1 is correct, if I increase the number of unique hashes plus increasing the bucket entries for each hash, will it allow better detection against millions of song / tracks? I think it will have tradeoff with performance / speed.

Thanks.

**Comment by dpwe** [comment]
>
>
>
>    1.
>
>    Considerng current implementation of HashTable, which holds 1,048,576
>    unique hashes with each hash holds 100 entries, you've explained that this
>    configuration is able to store more than 100k song tracks. If I have
>    millions of song tracks, would it lessen the accuracy of detection against
>    all the millions of song tracks? Because I understand that when the bucket
>    is filled (over 100 entries) for a specific hash, that specific hash's
>    bucket it gets randomly replaced in a random position of the entries
>    between 1 to 100 (replaced by new song / track id).
>
> Yes, there is a gradual reduction in matching accuracy as the hash table
becomes full.  I haven't quantified this, but note that it isn't
necessarily as bad as it appears: the less-common hashes are the last ones
to fill up, but they are also the most discriminant ones.  The hashes that
are dropped are, by definition, the hashes that occur in the greatest
number of tracks, so provide the least discrimination among tracks.

However, once a majority of the hash bins are full, this argument doesn't
hold.  But, if we drop 50% of the hashes, we still have the chance to match
the other ~50% of hashes for each reference item.  So the threshold for
missing a match goes up, but it still mostly works.



>
>    1.
>    2.
>
>    If number 1 is correct, if I increase the number of unique hashes plus
>    increasing the bucket entries for each hash, will it allow better detection
>    against millions of song / tracks? I think it will have tradeoff with
>    performance / speed.
>
> Yes; once the percent-dropped-hashes grows to more than 5 or 10, matching
efficiency (i.e. the shortest or noisiest clip that can be successfully
matched) goes down.  Increasing the bucket size so that fewer hashes are
dropped will fix this.

In general, you can vary the number of hashes stored per track with
density, fanout, etc.  More hashes per track means better matching ability
(match shorter or noisier excerpts), but larger databases.  So there are
many interacting factors.

  DAn.
