### ISSUE TITLE
Improve matches in pitch/tempo changing song samples

### ISSUE THREAD

**Issue by liorazi** [dpwe/audfprint#35]
There is a possibility this is one of the disadvantages of the algorithm used in audfprint, but is there a way to improve the match % in songs where the pitch/tempo was changed? (via the Options?)

According to what I tested (using Ableton) if you change pitch >-/+1% songs start to be not matchable. Same goes to changing tempo only (preserving the key) with >-/+ 5%.

-Lior

**Comment by dpwe** [comment]
That's right, the algorithm is acutely sensitive to the exact timing and
tuning of the original, so if they are changed, the matching falls apart.

I've seen some work on designing fingerprints that were invariant to either
or both of tempo or pitch shifts, but they would be more expensive, and
presumably less discriminative (since there are now many possible matching
waveforms).  E.g. http://www.ofai.at/research/impml/technology/identify.html

When I wanted to deal with the possibility of substantial playback speed
change in the past, I added multiple resampled versions of the reference to
my database (since in many applications the reference database has plenty
of room to spare).  That way you only span the ranges and combinations of
scalings you care about.  Spacing them e.g. 1% apart will provide the
ability to match any factors within the range.

Good luck!

  DAn.

**Comment by liorazi** [comment]
Cool, that answered my needs.

Thanks for the quick reply!

-Lior
