### ISSUE TITLE
Accuracy when compared to other popular audio fingerprinting library - dejavu?

### ISSUE THREAD

**Issue by kafan1986** [dpwe/audfprint#36]
Did someone here test accuracy of this library when compared to dejavu audio fingerprinting. Did the author introduced any new concept to improve the accuracy?

**Comment by dpwe** [comment]
I don’t know of any comparison. It’s the same basic approach but there are
a lot of details. Audfprint uses a very simple in-memory table instead of a
real database; this was done to be fast, but I never actually tried a
database engine.

If you do compare them head-to-head, let us know!  Aspects to consider:

 - analysis compute cost
 - matching compute cost
 - accuracy vs. sample duration
 - accuracy vs. noise level
 - accuracy vs. sub-frame time skew
 - accuracy vs. size of reference table. In audfprint this reflects
parameters like density and fanout, and parallels matching compute cost.

For fair accuracy comparisons, you probably need to tune systems to have
equal reference database size, or match compute, or something. It’s easy to
get better match accuracy if you’re using denser landmarks, but there are
usually practical constraints.

  DAn.

**Comment by amoose136** [comment]
I tried for a few hours to get dejavu working but mysql was not being cooperative on my mac. I got this working with non example input files in about an hour. Most setbacks were just due to making sure my python libraries were up to date and correctly linked.
