### ISSUE TITLE
Memory Error when writing out 50k tracks on a 1GB machine

### ISSUE THREAD

**Issue by brewsterkahle** [dpwe/audfprint#5]
When I upped the machine to 3GB of virtual memory, it worked fine.    I tried using the --addcheckpoint to see if I could write it out before it got to large, but it did not seem to be a recognized command line option in the newest release.

The real time to search 50k tracks with a 10 second clip when in a docker container   (rajbot/audfprint) was 11seconds.

-brewster

**Comment by dpwe** [comment]
Because of the shockingly naive "database" I used (a fixed, rectangular table), the memory usage does not depend on the number of tracks being ingested.  It will, however, be stretched by an unusually long-duration input file.  

I've added modifications in the latest release (from the "ia" branch) that reduce the memory usage to better handle long files, as well as an option to simply skip files if there are problems reading them.  Unfortunately, there's no good way at present to recover the results of an incomplete run, or to automatically skip over adding files that already exist in a database.

One approach is to run a two-stage ingestion: first precompute landmark feature files for each input audio file (audfprint precompute ...), then build the database from those feature files instead of from the original audio.  Using "audfprint precompute ... --skip-existing ..." *will* skip recomputing the landmark features for input audio files where it sees that the output feature file already exists.
