### ISSUE TITLE
Multiple input and adding live audio option

### ISSUE THREAD

**Issue by asimejaz14** [dpwe/audfprint#76]
Hey man, I've been using this for few days. Works all good but I have few issues,

1- Is there a way to add multiple input files like a list to match audios in our database? currently I can only give one input audio as an argument.

2- Is there a way to convert it to simple input output python program without using command line arguments? Its so frustrating sometimes to write complete command again and again

3- Is there a way to add live audio capture like matching live radio for our ads already stored in database?

**Comment by dpwe** [comment]
> 1- Is there a way to add multiple input files like a list to match audios
> in our database? currently I can only give one input audio as an argument.
>

Yes, with the --list option, each input file is treated as a list of paths
to wav files, one per line.

> 2- Is there a way to convert it to simple input output python program
> without using command line arguments? Its so frustrating sometimes to write
> complete command again and again
>
You can edit the declaration of the command line flags in the USAGE
variable (i.e.,
https://github.com/dpwe/audfprint/blob/master/audfprint.py#L354 and
onwards) to have the defaults you want to use instead of having to specify
them.  I use the docopts package which actually parses the USAGE message to
figure out what the acceptable flags are, and their default values (occur
in square brackets at the end of the line describing each flag).

> 3- Is there a way to add live audio capture like matching live radio for
> our ads already stored in database?
>
That would be a lot more involved.  The matching is intrinsically batch
mode; you'd need to set up a job to capture, e.g., 1 min clips of the live
input, then save them to disk and pass them to the query system.

  DAn.

**Comment by asimejaz14** [comment]
@dpwe About your answer to question 1
Can you please specify the syntax of giving multiple input audios.

Right now, I do this

> match --dbase ads_database.pklz audio_1.mp3 --find-time-range --maxtimebits 18

But I want something like this,

> match --dbase ads_database.pklz  aduio_1.mp3, audio_2.mp3, audio_3.mp3 --find-time-range --maxtimebits 18

I hope this makes sense.

**Comment by asimejaz14** [comment]
Thanks bro! List option worked perfect and I was successfully able to input multiple files as input. :+1:  

Also, thanks for ques 2 and 3 as well. I will look into it.

**Comment by dpwe** [comment]
Specifying multiple audio files on the command line should work.  Separate
them with a space, and don't use commas.

  DAn.
