### ISSUE TITLE
samplerate test

### ISSUE THREAD

**Issue by apiszcz** [dpwe/audfprint#9]
I tested the samplerate for ingest of content and query values as follows. Note Case 1 is correct. All source data is original 8KHZ. 
 --exact-count
 --min-count 1
 --density 100
 --max-matches 10
 --match-win 5
 --pks-per-frame 2

Case1:--samplerate 11000, first case is the query itself in the content, second instance is a match, 62.1 seconds is another instance, All detections in case 1 are correct.
<pre>
at 46.476 s with 2 of 9 hashes at rank 1
at 47.686 s with 1 of 9 hashes at rank 1
at 62.183 s with 1 of 9 hashes at rank 1
</pre>

Case 2: Here we have a match with itself, however it misses matches at 47.6 and 62 in the top 10 results.

With 8KHZ data --samplerate 8000
<pre>
 at 46.048 s with 3 of 13 hashes at rank 1
 at 332.416 s with 2 of 13 hashes at rank 1
 at 12.672 s with 1 of 13 hashes at rank 1
 at 13.472 s with 1 of 13 hashes at rank 1
 at 97.408 s with 1 of 13 hashes at rank 1
 at 121.056 s with 1 of 13 hashes at rank 1
 at 146.304 s with 1 of 13 hashes at rank 1
 at 257.216 s with 1 of 13 hashes at rank 1
 at 323.008 s with 1 of 13 hashes at rank 1
</pre>

**Comment by dpwe** [comment]
The numbers of matching and total hashes look extremely small. I wouldn't
trust any matches with fewer than 5-10 hash matches - 1 or 2 hashes are
very likely due to coincidences.

You should up your density until you're getting at least 20-40 total hashes
in your test segments. Also, it's not going to work well with very short
match patterns - I'd say 2 sec was a minimum.  Single words sound too
little, and I don't really understand the use-case.  Why would such a short
segment be repeated exactly?

It absolutely won't match different instances of the same word, even spoken
by the same speaker. That's a different recognition problem.

  DAn.

**Comment by apiszcz** [comment]
Thank you for the feedback, use case is fingerprint detection on short
segments, I'm exploring parameter ranges for reasonable hit rates. Agree,
2-4 seconds seems more reasonable. Recognition, understand.
